CREATE SEQUENCE administrator_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE application_type_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE application_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE classroom_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE course_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE enrollment_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE faculty_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE learning_materials_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE lecturer_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE message_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE partial_mark_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE payment_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE scheduled_classes_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE scholarship_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE student_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE students_group_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE subject_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE transcript_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;

CREATE SEQUENCE university_id_seq
START WITH 1 INCREMENT BY 1 NO CYCLE;